<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Whitelist Request Form</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Whitelist Request Form</a></h1>
		<form id="form_48925" class="appnitro"  method="GET" action="whitelist.php">
					<div class="form_description">
			<h2>Whitelist Request Form</h2>
			<p>Please fill out this form if are having issues accessing a website.</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Name </label>
		<div>
			<input id="element_1" name="element_1" class="element text medium" type="text" maxlength="255" value="" required/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Email </label>
		<div>
			<input id="element_2" name="element_2" class="element text medium" type="text" maxlength="255" value="" required/> 
		</div> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Domain(s) to be whitelisted </label>
		<div>
			<textarea id="element_3" name="element_3" class="element textarea medium" required></textarea> 
		</div><p class="guidelines" id="guide_3"><small>Please enter the domains to be whitelisted, one per line please, otherwise your request may take longer to process.</small></p> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="48925" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>
